default: styles/mastodon-bird-ui-auto.scss
mastodon-dark: styles/application.scss
mastodon-bird-ui-accessible: styles/mastodon-bird-ui-accessible.scss
mastodon-bird-ui-accessible-plus: styles/mastodon-bird-ui-accessible-plus.scss
